import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parseCsv } from '../src/data/csvLoader.js';
import { candidateSize, formatDistance, groupAnchors, kindLabel } from '../src/analysis/anchors.js';

const rows = [
  { place: 'home', kind: 'park', name: 'Far Park', status: 'candidate', distance_mi: '1', detail: 'leisure=park, ~6 acres', fetched_on: '2026-09-17', source: 'OSM' },
  { place: 'home', kind: 'stream', name: 'Near Creek', status: 'anchor', distance_mi: '0.75', detail: 'channel', fetched_on: '2026-09-17', source: 'NHD' },
  { place: 'home', kind: 'park', name: 'Close Park', status: 'candidate', distance_mi: '0.25', detail: 'leisure=park, ~8 acres', fetched_on: '2026-09-18', source: 'OSM' },
  { place: 'home', kind: 'cemetery', name: 'Also Close', status: 'candidate', distance_mi: '0.25', detail: '', fetched_on: '2026-09-17', source: 'OSM' },
  { place: 'elsewhere', kind: 'stream', name: 'Other Creek', status: 'anchor', distance_mi: '0.5', detail: '', fetched_on: '2026-09-17', source: 'NHD' },
  { place: 'home', kind: 'park', name: '', status: 'candidate', distance_mi: '0.5', detail: '', fetched_on: '2026-09-17', source: 'OSM' },
  { place: 'home', kind: 'park', name: 'No Distance', status: 'candidate', distance_mi: '', detail: '', fetched_on: '2026-09-17', source: 'OSM' },
];

test('groupAnchors splits mapped anchors from unchecked candidates for one place', () => {
  const { anchors, candidates } = groupAnchors(rows, 'home');
  assert.deepEqual(anchors.map((a) => a.name), ['Near Creek']);
  assert.deepEqual(candidates.map((c) => c.name), ['Also Close', 'Close Park', 'Far Park']);
});

test('groupAnchors orders by distance only, ties by name, and drops rows it cannot show honestly', () => {
  const { candidates } = groupAnchors(rows, 'home');
  assert.deepEqual(candidates.map((c) => c.distanceMi), [0.25, 0.25, 1]);
  assert.ok(!candidates.some((c) => c.name === 'No Distance' || c.name === ''));
});

test('groupAnchors reports the newest fetch date and nothing for an unknown or empty place', () => {
  assert.equal(groupAnchors(rows, 'home').fetchedOn, '2026-09-18');
  assert.deepEqual(groupAnchors(rows, 'nowhere'), { anchors: [], candidates: [], fetchedOn: '' });
  assert.deepEqual(groupAnchors(rows, ''), { anchors: [], candidates: [], fetchedOn: '' });
  assert.deepEqual(groupAnchors(null, 'home'), { anchors: [], candidates: [], fetchedOn: '' });
});

test('display helpers', () => {
  assert.equal(formatDistance(0.75), '0.75 mi');
  assert.equal(formatDistance(1), '1 mi');
  assert.equal(kindLabel('nature_reserve'), 'nature reserve');
  assert.equal(kindLabel('something_new'), 'something new');
  assert.equal(candidateSize('leisure=park, ~8 acres'), '~8 acres');
  assert.equal(candidateSize('landuse=cemetery, ~29 acres'), '~29 acres');
  assert.equal(candidateSize('channel'), '');
});

test('the committed anchors.csv parses into both groups for place "home"', () => {
  const csv = readFileSync(fileURLToPath(new URL('../ecology/anchors.csv', import.meta.url)), 'utf8');
  const { anchors, candidates } = groupAnchors(parseCsv(csv), 'home');
  // Shape, not content: the table is regenerated by the fetch tools.
  assert.ok(anchors.every((a) => a.kind === 'stream' && a.status === 'anchor'));
  assert.ok(candidates.every((c) => c.status === 'candidate'));
  assert.ok(anchors.length + candidates.length > 0);
});
