import test from 'node:test';
import assert from 'node:assert/strict';
import { buildCloneId, buildDriftId, buildNewPlantId, DRIFT_ID_MAX_LENGTH, isValidDriftId } from '../src/state/plantIds.js';
import { parsePlantLayoutCsv } from '../src/data/plantParser.js';

test('a clone never reuses an id already in the layout', () => {
  const plants = [{ id: 'sage' }, { id: 'daisy' }];

  assert.equal(buildCloneId(plants, 'sage'), 'sage-copy');
});

test('repeated clones of the same plant keep walking past collisions', () => {
  const plants = [{ id: 'sage' }, { id: 'sage-copy' }, { id: 'sage-copy-2' }];

  assert.equal(buildCloneId(plants, 'sage'), 'sage-copy-3');
});

test('cloning a clone stays distinct from every existing id', () => {
  const plants = [{ id: 'sage' }, { id: 'sage-copy' }];

  assert.equal(buildCloneId(plants, 'sage-copy'), 'sage-copy-copy');
});

test('ids generated by cloning survive the layout uniqueness check', () => {
  // The two guards have to agree: whatever cloning mints must parse back in.
  let plants = [{ id: 'sage' }];
  for (let i = 0; i < 5; i++) {
    plants = [...plants, { id: buildCloneId(plants, 'sage') }];
  }

  const csv = 'id,botanical_name,x_ft,y_ft\n'
    + plants.map((p) => `${p.id},Salvia greggii,1,1`).join('\n');

  assert.doesNotThrow(() => parsePlantLayoutCsv(csv));
  assert.equal(new Set(plants.map((p) => p.id)).size, plants.length);
});

test('a plant added from the catalog is named after its species', () => {
  const plants = [{ id: 'sage' }];

  assert.equal(buildNewPlantId(plants, 'Salvia greggii'), 'salvia-greggii-1');
});

test('adding the same species repeatedly keeps walking past collisions', () => {
  const plants = [{ id: 'salvia-greggii-1' }, { id: 'salvia-greggii-2' }];

  assert.equal(buildNewPlantId(plants, 'Salvia greggii'), 'salvia-greggii-3');
});

test('a species name with no usable characters still yields a valid id', () => {
  assert.equal(buildNewPlantId([], '   '), 'plant-1');
});

test('ids generated by adding survive the layout uniqueness check', () => {
  // Same contract as cloning: whatever the add path mints must parse back in,
  // and must not collide with an id cloning produced either.
  let plants = [{ id: 'salvia-greggii-1' }];
  for (let i = 0; i < 4; i++) {
    plants = [...plants, { id: buildNewPlantId(plants, 'Salvia greggii') }];
    plants = [...plants, { id: buildCloneId(plants, 'salvia-greggii-1') }];
  }

  const csv = 'id,botanical_name,x_ft,y_ft\n'
    + plants.map((p) => `${p.id},Salvia greggii,1,1`).join('\n');

  assert.doesNotThrow(() => parsePlantLayoutCsv(csv));
  assert.equal(new Set(plants.map((p) => p.id)).size, plants.length);
});

test('isValidDriftId accepts a bounded lowercase slug and rejects everything else (nl-o47.6.1)', () => {
  assert.equal(isValidDriftId('winecup-strip'), true);
  assert.equal(isValidDriftId('winecup_strip_2'), true);
  assert.equal(isValidDriftId('a'), true);
  assert.equal(isValidDriftId('x'.repeat(DRIFT_ID_MAX_LENGTH)), true);
  assert.equal(isValidDriftId('x'.repeat(DRIFT_ID_MAX_LENGTH + 1)), false, 'over the max length');
  assert.equal(isValidDriftId(''), false, 'empty');
  assert.equal(isValidDriftId('Winecup-Strip'), false, 'uppercase');
  assert.equal(isValidDriftId('winecup strip'), false, 'a space');
  assert.equal(isValidDriftId('-winecup'), false, 'leading hyphen');
  assert.equal(isValidDriftId(null), false);
  assert.equal(isValidDriftId(undefined), false);
  assert.equal(isValidDriftId(42), false);
});

test('a new drift is named after the label given it, and never collides', () => {
  assert.equal(buildDriftId([], 'Winecup strip'), 'winecup-strip');
  assert.equal(buildDriftId(['winecup-strip'], 'Winecup strip'), 'winecup-strip-2');
  assert.equal(buildDriftId(['winecup-strip', 'winecup-strip-2'], 'Winecup strip'), 'winecup-strip-3');
});

test('a drift label with no usable characters still yields a valid id', () => {
  assert.equal(buildDriftId([], '   '), 'drift');
  assert.equal(buildDriftId(['drift'], ''), 'drift-2');
});

test('every id buildDriftId mints passes isValidDriftId, even at the length bound', () => {
  const longLabel = 'a'.repeat(200);
  let existing = [];
  for (let i = 0; i < 5; i++) {
    const id = buildDriftId(existing, longLabel);
    assert.ok(isValidDriftId(id), `"${id}" is not a valid drift id`);
    assert.ok(!existing.includes(id), 'must not collide');
    existing = [...existing, id];
  }
});
